---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/willisc7/basic-concourse-pipeline.git
    branch: master

- name: resource-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/tasks/task_run_tests.yml
